# Generated by Django 4.1.2 on 2022-10-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
