# Generated by Django 4.1.2 on 2022-10-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('students', models.ManyToManyField(related_name='subjects', to='student.student')),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='student.parent'),
        ),
    ]
