# Generated by Django 4.1.2 on 2022-10-25 04:01

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_parent_subject_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=70, validators=[student.models.validate_first_name]),
        ),
    ]
