# Generated by Django 4.1.2 on 2022-10-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_parent_first_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('first_name__startswith', 'm')), name='not starts with m'),
        ),
    ]
