# Generated by Django 4.1.2 on 2022-10-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_not starts with m'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='not starts with m',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('first_name__istartswith', 'm')), name='not starts with m'),
        ),
    ]
