# Generated by Django 4.1.2 on 2022-10-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_parent_email_parent_password_student_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticationKey', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'ActiveUsers',
            },
        ),
    ]
