# Generated by Django 4.1.2 on 2022-10-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_activeusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentActiveUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticationKey', models.CharField(max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activeUsers', to='student.parent')),
            ],
            options={
                'db_table': 'ParentActiveUsers',
            },
        ),
        migrations.CreateModel(
            name='StudentActiveUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticationKey', models.CharField(max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activeUsers', to='student.student')),
            ],
            options={
                'db_table': 'StudentActiveUsers',
            },
        ),
        migrations.DeleteModel(
            name='ActiveUsers',
        ),
    ]
