# Generated by Django 4.1.2 on 2022-10-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_parentactiveusers_studentactiveusers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentactiveusers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activeUsers', to='student.parent'),
        ),
    ]
