# Generated by Django 4.1.2 on 2022-10-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_parentactiveusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactiveusers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activeUsers', to='student.student'),
        ),
    ]
